gold_data_dir: "D:/Hao/Desktop/冰冻圈水文/北极大河/arctic_doc_data_audit/data/processed/gold"
gold_reports_dir: "D:/Hao/Desktop/冰冻圈水文/北极大河/arctic_doc_data_audit/outputs/reports/gold"
gold_tables_dir: "D:/Hao/Desktop/冰冻圈水文/北极大河/arctic_doc_data_audit/outputs/tables/gold"
